### ISSUE TITLE
Use a distroless image 

### ISSUE THREAD

**Issue by floriankoch** [AmitKumarDas/metac#106]
What do you think of using https://github.com/GoogleContainerTools/distroless as a base image instead of debian slim?

**Comment by grzesuav** [comment]
Need to be very careful, as it makes debugging (exec into running container) impossible

**Comment by floriankoch** [comment]
@grzesuav  yes and no - you can use the :debug variant, with a busybox included

**Comment by AmitKumarDas** [comment]
I will change it to distroless image or would love to accept any PRs on the same.
In fact I have been using distroless image for my other projects without issues.

Refer - https://github.com/mayadata-io/cstorpoolauto/blob/master/Dockerfile

**Comment by floriankoch** [comment]
@AmitKumarDas i will send a PR

**Comment by grzesuav** [comment]
I would say both variant should be present. Also @floriankoch if you wish to have :debug version of metacontroller it should also be distributed (basing on :debug go distroless image)

**Comment by AmitKumarDas** [comment]
Trying to get my head around debug stuff. I hope log levels do help here. I/we are taking extra steps to unit test everything before pushing a PR. We need to think about exposing operational metrics soon.

However do we feel there might be circumstances where we need to attach a debugger to the running container and hence the need for a debug binary? Or is it something that I am not getting.

**Comment by grzesuav** [comment]
@AmitKumarDas it is not only about attaching debuger, with distroless there is no shell/package manager so basically you cannot do anything with that process.

 I know that in k8s there are plans for ephemeral containers but :
* it is not there yet
* there would be a long transition time for people to move their cluster to target version anyway (having that feature)

**Comment by AmitKumarDas** [comment]
Having two images makes sense then.
