### ISSUE TITLE
sample-controller does not work on kubernetes 1.16+

### ISSUE THREAD

**Issue by floriankoch** [AmitKumarDas/metac#127]
The sample-controller uses  foos.samplecontroller.k8s.io

With newer kubernetes versions, the k8s.io namespace is protected
see https://github.com/kubernetes/enhancements/pull/1111

I suggest to switch to foos.samplecontroller.example.io

Is this the way forward?

**Comment by AmitKumarDas** [comment]
thanks @floriankoch this is a good find.
We can proceed with above group name i.e. `foos.samplecontroller.example.io`
