### ISSUE TITLE
Ability to precondition/construct kubernetes resources by pulling definition from a custom resource

### ISSUE THREAD

**Issue by ksatchit** [AmitKumarDas/metac#17]
### USECASE 

The [chaos executor](https://github.com/litmuschaos/litmus/tree/master/executor) is a playbook (itself run as a pod/job) that reads some information (mostly, ENV) from a CR called [chaosExperiment](https://github.com/litmuschaos/community-charts/blob/master/charts/kubernetes/state/experiments/pod-delete-exp.version.yaml), constructs a data structure (list of key:value pairs) and uses this info to precondition an existing job manifest (a chaos job: which looks like [this](https://github.com/litmuschaos/litmus/blob/master/experiments/chaos/kubernetes/pod_delete/run_litmus_test.yml)). This is done by doing a `kubectl set env -f <job manifest> --dry-run -o yaml > <preconditioned-job-manifest>.yml`. 

The current approach is very limiting, considering that it can only precondition job wrt ENVs. It is possible that the experiment CR needs to inject more complex data into the job via configmaps, secrets, persistent volumes etc., (being a CR, we have no end to our imagination wrt how we want to expand the spec & what we want to inject into the job)  

Ex: When there are jobs such as [this](https://github.com/litmuschaos/litmus/blob/master/experiments/chaos/openebs_target_network_delay/run_litmus_test.yml), the `set env` based approach doesn't work. One of the workarounds used was to extract desired info from the experiment CR & create those resources imperatively using `kubectl run`. 

### REQUIREMENT

Have a generic way to insert spec into a manifest or an un-created resource. OR in other words, construct the spec of a resource by reading another.

**Comment by AmitKumarDas** [comment]
Thanks @ksatchit for the usecase.

Is it exepcted to have the configmaps, secrets, persistentvolumes to be already available when this experiment is applied. In other words, given an experiment a Job needs to be created. Job in turn might need several other resources like configmaps, secrets, pv etc

**Comment by AmitKumarDas** [comment]
@ksatchit You may want to try out some examples in this repository. Perhaps that will help you understand more in terms of how Metac works. I am sure, we can figure out suitable controllers for your requirements.

**Comment by AmitKumarDas** [comment]
These examples should provide some ideas:
https://github.com/AmitKumarDas/metac/tree/master/examples
