### ISSUE TITLE
docs: Add link to docker image

### ISSUE THREAD

**Issue by grzesuav** [AmitKumarDas/metac#66]
Could not find any reference ti dockerhub image, please add it to the README

**Comment by AmitKumarDas** [comment]
https://github.com/AmitKumarDas/metac/blob/master/manifests/metacontroller.yaml#L80

It's at quay. It's public. Will it be possible for you to verify and update the readme. Alternatively will see if I can make some time tomorrow.

**Comment by AmitKumarDas** [comment]
@grzesuav Please check if following helps?
https://github.com/AmitKumarDas/metac/pull/68
