### ISSUE TITLE
Change log level from 4 to 5 for the logic that logs last applied annotation

### ISSUE THREAD

**Issue by AmitKumarDas** [AmitKumarDas/metac#82]
_**Problem Statement:**_ Following block of code should be modified to use log level 5 instead of log level 4. This log seems to be extra debug info & can be treated on same level as hook response received from hook invocations.

https://github.com/AmitKumarDas/metac/blob/master/dynamic/apply/apply.go#L80-L87

**Comment by floriankoch** [comment]
Its merged so this issue can closed?
